# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pip
      run: python -m pip install --upgrade pip
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install ANTLR4
      run: pip install antlr4-tools
    - name: Install Dependencies
      run: cd ./GameTheoryLanguage/ && dotnet add package Antlr4.Runtime.Standard --version 4.13.1
    - name: Restore dependencies
      run: dotnet restore
    - name: run antlr
      run: cd .\Build && antlr4 -Dlanguage=CSharp -visitor -no-listener -o out Gtl.g4
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test
