# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install ANTLR4
      uses: siacodelabs/setup-antlr4@v2
    - name: run ANTLR4
      run: cd ./GameTheoryLanguage/Parser && antlr4 -Dlanguage=CSharp -visitor -no-listener -o out Gtl.g4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Parser tests
      run: dotnet test --filter "Classname=GameTheoryLanguageTests.ParserTests"
    - name: Typechecking tests
      run: dotnet test --filter "Classname=GameTheoryLanguageTests.TypecheckingTests"
    - name: Transpiler tests
      run: dotnet test --filter "Classname=GameTheoryLanguageTests.TranspilerTests"
    - name: EndToEnd tests
      run: dotnet test --filter "FullyQualifiedName=GameTheoryLanguageTests.EndToEndTests.SetupTests" && cd ./GameTheoryLanguageTests/EndToEndTests && cargo test
